background {
    monitor =
    path = /usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/astronaut.png
    blur_passes = 2
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 4
    outer_color = rgba(ffffffff)
    inner_color = rgba(000000ff)
    font_color = rgba(ffffffff)
    placeholder_text = Enter Password
    hide_input = false
    rounding = 10
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 72
    font_family = Open Sans
    color = rgba(ffffffff)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A %-d %B"
    font_size = 18
    font_family = Open Sans
    color = rgba(ffffffff)
    position = 0, 60
    halign = center
    valign = center
}
